version: 2

models:
  - name: stg_customers
    columns: 
      - name: customer_id
        tests:
          - not_null
          - unique
  - name: stg_orders
    columns:
      - name: order_id
        tests:
          - not_null
          - unique
      - name: status
        tests:
          - accepted_values:
              values: ['completed', 'return_pending', 'shipped', 'placed', 'returned']
  - name: stg_payments
    columns:
      - name: payment_id
        tests:
          - not_null
          - unique
      - name: payment_method
        tests:
          - accepted_values:
              values: ['credit_card', 'coupon', 'bank_transfer', 'gift_card']